apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xtemplates.example.org
spec:
  group: example.org
  names:
    kind: XTemplate
    plural: xtemplates
  claimNames:
    kind: Template
    plural: templates
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  description: Template configuration parameters.
                  properties:
                    region:
                      type: string
                      description: Region is the region you'd like your resource to be created in.
                    providerConfigName:
                      description: Crossplane ProviderConfig to use for provisioning this resources.
                      type: string
                      default: default
                    deletionPolicy:
                      description: Delete the external resources when the Claim/XR is deleted. Defaults to Delete.
                      enum:
                        - Delete
                        - Orphan
                      type: string
                      default: Delete
                    versioning:
                      type: boolean
                      description: Boolean fields to enable or disable versioning.
